# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in wikidotrb.gemspec
gemspec

gem "rake", "~> 13.0"
gem "rspec", "~> 3.0"
gem "rubocop", "~> 1.21"

gem "httpx", "~> 0.2"
gem 'http-cookie', '~> 1.0'
gem "nokogiri", "~> 1.12"
gem "concurrent-ruby", "~> 1.1"
gem "json", "~> 2.0"
gem "logger", "~> 1.4"
gem "date"
