# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in wikidotrb.gemspec
gemspec

gem "rake", "~> 13.0"
gem "rspec", "~> 3.10"
gem "rubocop", "~> 1.21"

gem "base64"
gem "mutex_m"

group :test do
  gem "rspec_junit_formatter"
end

group :development, :documentation do
  gem "yard", "~> 0.9.34"
  gem "rdoc", "~> 7.0"
  gem "rbs", "~> 3.1"
  gem "redcarpet", "~> 3.6"
  # Removed server dependencies - using static generation only
end
